const SUPABASE_URL="https://mqkoiyqaeyoiefeoxusy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_Il7ZpPjVF9nRWc6Him0uFg_AN59J6li";
const BUCKET="music";
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
const input=$("fileInput"),coverInput=$("coverInput"),chooseCover=$("chooseCover"),coverName=$("coverName"),uploadLabel=$("uploadLabel");
const audio=$("audio"),play=$("play"),seek=$("seek"),current=$("current"),duration=$("duration"),nowTitle=$("nowTitle"),nowArtist=$("nowArtist"),nowCover=$("cover"),count=$("count"),statusBox=$("status"),search=$("search");
let songs=[],index=-1,selectedCover=null,favorites=new Set(),playlists=[],currentView="home",playlistDetailId=null,queue=[],queuePos=-1,currentObjectUrl=null;
let shuffleOn=localStorage.getItem("miMusicaShuffle")==="1",repeatOn=localStorage.getItem("miMusicaRepeat")==="1";
const OFFLINE_DB="miMusicaOffline",OFFLINE_STORE="audio",CURRENT_KEY="miMusicaCurrentSong";
const fmt=s=>!isFinite(s)?"0:00":Math.floor(s/60)+":"+String(Math.floor(s%60)).padStart(2,"0");
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function status(msg,error=false){if(!statusBox)return;statusBox.textContent=msg;statusBox.classList.remove("hidden");statusBox.classList.toggle("error",error);clearTimeout(status.timer);if(!error)status.timer=setTimeout(()=>statusBox.classList.add("hidden"),3500)}
function session(){return supabaseClient.auth.getSession().then(r=>r.data.session)}
function offlineMetaKey(uid){return `miMusicaOfflineMeta:${uid}`}
function saveOfflineMeta(uid,list){try{localStorage.setItem(offlineMetaKey(uid),JSON.stringify(list))}catch{}}
function loadOfflineMeta(uid){try{return JSON.parse(localStorage.getItem(offlineMetaKey(uid))||"[]")}catch{return[]}}
function openOfflineDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(OFFLINE_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(OFFLINE_STORE))r.result.createObjectStore(OFFLINE_STORE,{keyPath:"id"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getOfflineAudio(id){try{const db=await openOfflineDB();return await new Promise((resolve,reject)=>{const q=db.transaction(OFFLINE_STORE,"readonly").objectStore(OFFLINE_STORE).get(id);q.onsuccess=()=>{db.close();resolve(q.result?.blob||null)};q.onerror=()=>{db.close();reject(q.error)}})}catch{return null}}
async function saveOfflineAudio(id,blob){const db=await openOfflineDB();return new Promise((resolve,reject)=>{const tx=db.transaction(OFFLINE_STORE,"readwrite");tx.objectStore(OFFLINE_STORE).put({id,blob,cachedAt:Date.now()});tx.oncomplete=()=>{db.close();resolve(true)};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function removeOfflineAudio(id){try{const db=await openOfflineDB();return await new Promise((resolve,reject)=>{const tx=db.transaction(OFFLINE_STORE,"readwrite");tx.objectStore(OFFLINE_STORE).delete(id);tx.oncomplete=()=>{db.close();resolve(true)};tx.onerror=()=>{db.close();reject(tx.error)}})}catch{return false}}
async function isOffline(id){return !!(await getOfflineAudio(id))}
async function cacheSongOffline(id){const s=songs.find(x=>x.id===id);if(!s)return false;if(await getOfflineAudio(id))return true;const r=await supabaseClient.storage.from(BUCKET).createSignedUrl(s.storage_path,3600);if(r.error)throw r.error;const res=await fetch(r.data.signedUrl);if(!res.ok)throw new Error("No se pudo descargar el audio.");await saveOfflineAudio(id,await res.blob());return true}
function uploadEnabled(ok){if(uploadLabel){uploadLabel.style.opacity=ok?"1":".55";uploadLabel.style.pointerEvents=ok?"auto":"none"}if(chooseCover){chooseCover.disabled=!ok;chooseCover.style.opacity=ok?"1":".55"}}
async function coverUrl(s){if(!s?.cover_path)return null;const r=await supabaseClient.storage.from(BUCKET).createSignedUrl(s.cover_path,3600);return r.error?null:r.data?.signedUrl||null}
function filterSongs(v){const q=String(v||"").trim().toLowerCase();return q?songs.filter(s=>(s.title||"").toLowerCase().includes(q)||(s.artist||"").toLowerCase().includes(q)):songs}
async function sortList(list){const mode=$("sortSelect")?.value||"new";const a=[...list];if(mode==="az")a.sort((x,y)=>(x.title||"").localeCompare(y.title||"","es",{sensitivity:"base"}));if(mode==="artist")a.sort((x,y)=>(x.artist||"").localeCompare(y.artist||"","es",{sensitivity:"base"}));if($("offlineFilter")?.value==="offline"){const flags=await Promise.all(a.map(s=>isOffline(s.id)));return a.filter((_,i)=>flags[i])}return a}
function targetForView(){if(currentView==="search")return $("searchLibrary");if(currentView==="favorites")return $("favoritesLibrary");if(currentView==="playlistDetail")return $("playlistDetailSongs");return $("library")}
async function renderSongs(list,title="Biblioteca",target=targetForView()){if(!target)return;const sorted=await sortList(list);if(count)count.textContent=`${sorted.length} ${sorted.length===1?"canción":"canciones"}`;if(!sorted.length){target.innerHTML=`<div class="empty">No hay canciones para mostrar.</div>`;return}target.innerHTML=`${title?`<div class="section-title"><h2>${esc(title)}</h2><span>${sorted.length} ${sorted.length===1?"canción":"canciones"}</span></div>`:""}`+sorted.map(s=>`<div class="song"><div class="thumb" id="thumb-${s.id}">🎵</div><div class="song-info"><div class="song-title">${esc(s.title)}</div><div class="song-meta">${esc(s.artist||"Mi biblioteca")} <span class="offline-badge" id="offline-${s.id}"></span></div></div><div class="song-actions"><button title="Reproducir" onclick="playSongById('${s.id}')">▶</button><button title="Favorito" onclick="toggleFavorite('${s.id}')">${favorites.has(s.id)?"❤️":"🤍"}</button><button title="Editar" onclick="editSong('${s.id}')">✏️</button><button title="Agregar a playlist" onclick="addSongToPlaylist('${s.id}')">📋</button><button class="download" title="Guardar sin internet" onclick="downloadSongById('${s.id}')">⬇</button><button class="delete-song" title="Eliminar canción" onclick="deleteSong('${s.id}')">🗑️</button></div></div>`).join("");
await Promise.all(sorted.map(async s=>{const [u,off]=await Promise.all([coverUrl(s),isOffline(s.id)]);const el=$("thumb-"+s.id);if(u&&el)el.innerHTML=`<img src="${u}" alt="Portada">`;const b=$("offline-"+s.id);if(off&&b)b.textContent=" · 🟢 Sin conexión"}))}
async function loadSongs(){const s=await session();if(!s){songs=[];favorites.clear();playlists=[];renderSongs([]);uploadEnabled(false);updateProfile();return}uploadEnabled(true);const r=await supabaseClient.from("songs").select("*").order("created_at",{ascending:false});if(r.error){songs=loadOfflineMeta(s.user.id);await loadFavorites(true);await loadPlaylists(true);status(songs.length?"Sin conexión: mostrando tus canciones guardadas en este dispositivo.":"Sin conexión y no hay canciones disponibles.",!songs.length);if(currentView==="favorites")renderFavorites();else if(currentView==="playlists")renderPlaylists();else renderSongs(filterSongs(search?.value),currentView==="search"?"Resultados de búsqueda":"Biblioteca");return}songs=r.data||[];saveOfflineMeta(s.user.id,songs);await loadFavorites();await loadPlaylists();if(currentView==="favorites")renderFavorites();else if(currentView==="playlists")renderPlaylists();else if(currentView==="playlistDetail")await openPlaylistDetail(playlistDetailId,false);else if(currentView==="search")renderSongs(filterSongs(search?.value),"Resultados de búsqueda");else renderSongs(songs,"Biblioteca");updateProfile()}
if(chooseCover&&coverInput){chooseCover.onclick=()=>coverInput.click();coverInput.onchange=()=>{selectedCover=coverInput.files?.[0]||null;if(coverName)coverName.textContent=selectedCover?selectedCover.name:"Portada opcional"}}
if(input)input.onchange=async e=>{const s=await session();if(!s){alert("Primero inicia sesión desde Mi perfil.");input.value="";return}for(const file of [...e.target.files]){if(!file.type.startsWith("audio/"))continue;try{status("Subiendo "+file.name+"...");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=`${s.user.id}/${crypto.randomUUID()}-${safe}`;let r=await supabaseClient.storage.from(BUCKET).upload(path,file,{contentType:file.type||"audio/mpeg",upsert:false});if(r.error)throw r.error;let coverPath=null,coverMime=null;if(selectedCover){coverPath=`${s.user.id}/covers/${crypto.randomUUID()}-${selectedCover.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;r=await supabaseClient.storage.from(BUCKET).upload(coverPath,selectedCover,{contentType:selectedCover.type,upsert:false});if(r.error){await supabaseClient.storage.from(BUCKET).remove([path]);throw r.error}coverMime=selectedCover.type}r=await supabaseClient.from("songs").insert({user_id:s.user.id,title:file.name.replace(/\.[^/.]+$/,""),artist:"Mi biblioteca",storage_path:path,file_name:file.name,mime_type:file.type||"audio/mpeg",cover_path:coverPath,cover_mime_type:coverMime});if(r.error){await supabaseClient.storage.from(BUCKET).remove([path]);if(coverPath)await supabaseClient.storage.from(BUCKET).remove([coverPath]);throw r.error}}catch(err){status("No se pudo subir "+file.name+": "+err.message,true)}}input.value="";selectedCover=null;if(coverInput)coverInput.value="";if(coverName)coverName.textContent="Portada opcional";await loadSongs()}
async function playSongById(id){const i=songs.findIndex(s=>s.id===id);if(i<0)return;index=i;localStorage.setItem(CURRENT_KEY,id);const song=songs[i];if(currentObjectUrl)URL.revokeObjectURL(currentObjectUrl);currentObjectUrl=null;const cached=await getOfflineAudio(id);if(cached){currentObjectUrl=URL.createObjectURL(cached);audio.src=currentObjectUrl}else{const r=await supabaseClient.storage.from(BUCKET).createSignedUrl(song.storage_path,3600);if(r.error){status("Esta canción no está guardada para escucharla sin internet.",true);return}audio.src=r.data.signedUrl}nowTitle.textContent=song.title;nowArtist.textContent=song.artist||"Mi biblioteca";const u=await coverUrl(song);nowCover.innerHTML=u?`<img src="${u}" alt="Portada">`:"🎵";try{await audio.play()}catch{status("Pulsa ▶ para iniciar la reproducción.",true)}}window.playSongById=playSongById;
async function downloadSongById(id){try{status("Guardando para escuchar sin internet...");await cacheSongOffline(id);status("✅ Guardada. Ya puedes escucharla sin internet.");if(currentView==="search")renderSongs(filterSongs(search?.value),"Resultados de búsqueda",$("searchLibrary"));else if(currentView==="favorites")renderFavorites();else renderSongs(songs,"Biblioteca")}catch(e){status("No se pudo guardar sin conexión: "+e.message,true)}}window.downloadSongById=downloadSongById;
async function toggleFavorite(id){const s=await session();if(!s){alert("Primero inicia sesión.");return}let r;if(favorites.has(id)){r=await supabaseClient.from("favorites").delete().eq("song_id",id);if(!r.error)favorites.delete(id)}else{r=await supabaseClient.from("favorites").insert({user_id:s.user.id,song_id:id});if(!r.error)favorites.add(id)}if(r.error){status("No se pudo cambiar favorito: "+r.error.message,true);return}try{localStorage.setItem(`miMusicaOfflineFav:${s.user.id}`,JSON.stringify([...favorites]))}catch{}if(currentView==="favorites")renderFavorites();else if(currentView==="search")renderSongs(filterSongs(search?.value),"Resultados de búsqueda",$("searchLibrary"));else renderSongs(songs,"Biblioteca")}window.toggleFavorite=toggleFavorite;
async function loadFavorites(offlineOnly=false){const s=await session();if(!s)return;if(offlineOnly){try{favorites=new Set(JSON.parse(localStorage.getItem(`miMusicaOfflineFav:${s.user.id}`)||"[]"))}catch{favorites=new Set()}return}const r=await supabaseClient.from("favorites").select("song_id");if(!r.error){favorites=new Set((r.data||[]).map(x=>x.song_id));try{localStorage.setItem(`miMusicaOfflineFav:${s.user.id}`,JSON.stringify([...favorites]))}catch{}}}
function renderFavorites(){currentView="favorites";renderSongs(songs.filter(s=>favorites.has(s.id)),"Favoritos ❤️",$("favoritesLibrary"))}
async function loadPlaylists(offlineOnly=false){const s=await session();if(!s)return;if(offlineOnly){try{playlists=JSON.parse(localStorage.getItem(`miMusicaOfflinePlaylists:${s.user.id}`)||"[]")}catch{playlists=[]}return}const r=await supabaseClient.from("playlists").select("*").order("created_at",{ascending:false});if(!r.error){playlists=r.data||[];try{localStorage.setItem(`miMusicaOfflinePlaylists:${s.user.id}`,JSON.stringify(playlists))}catch{}}}
function playlistIcon(name){const icons=["📚","🎵","🔥","🌙","⭐","🎧","💿"];return icons[(String(name).length)%icons.length]}
async function renderPlaylists(){currentView="playlists";const box=$("playlists");if(!box)return;count.textContent=`${playlists.length} ${playlists.length===1?"playlist":"playlists"}`;box.innerHTML=playlists.length?playlists.map(p=>`<div class="playlist-row"><div class="playlist-icon">${playlistIcon(p.name)}</div><div class="song-info"><div class="song-title">${esc(p.name)}</div><div class="song-meta">Playlist</div></div><button onclick="openPlaylistDetail('${p.id}')">▶ Abrir</button><button onclick="renamePlaylist('${p.id}')">✏️</button><button onclick="deletePlaylist('${p.id}')">🗑️</button></div>`).join(""):"<div class=\"empty\">No tienes playlists todavía.</div>"}
window.renderPlaylists=renderPlaylists;
async function createPlaylist(){const s=await session();if(!s){alert("Primero inicia sesión.");return}$("playlistPanelTitle").textContent="Nueva playlist";$("playlistName").value="";$("playlistPanel").classList.remove("hidden");$("playlistPanel").dataset.mode="create"}
async function savePlaylist(){const s=await session();const name=$("playlistName").value.trim();if(!s||!name)return;const r=await supabaseClient.from("playlists").insert({user_id:s.user.id,name}).select().single();if(r.error){status("No se pudo crear: "+r.error.message,true);return}playlists.unshift(r.data);$("playlistPanel").classList.add("hidden");renderPlaylists()}
window.createPlaylist=createPlaylist;window.savePlaylist=savePlaylist;
async function renamePlaylist(id){const p=playlists.find(x=>x.id===id);if(!p)return;const name=prompt("Nuevo nombre:",p.name);if(name===null||!name.trim())return;const r=await supabaseClient.from("playlists").update({name:name.trim()}).eq("id",id);if(r.error){status("No se pudo renombrar: "+r.error.message,true);return}p.name=name.trim();renderPlaylists()}
window.renamePlaylist=renamePlaylist;
async function deletePlaylist(id){if(!confirm("¿Eliminar esta playlist? Las canciones no se borrarán."))return;const r=await supabaseClient.from("playlists").delete().eq("id",id);if(r.error){status("No se pudo eliminar: "+r.error.message,true);return}playlists=playlists.filter(p=>p.id!==id);if(playlistDetailId===id)showAppView("playlists");else renderPlaylists()}
window.deletePlaylist=deletePlaylist;
async function openPlaylistDetail(id,navigate=true){const p=playlists.find(x=>x.id===id);if(!p)return;playlistDetailId=id;if(navigate)showAppView("playlistDetail");const r=await supabaseClient.from("playlist_songs").select("song_id").eq("playlist_id",id);if(r.error){status("No se pudo abrir: "+r.error.message,true);return}const ids=(r.data||[]).map(x=>x.song_id);const list=songs.filter(s=>ids.includes(s.id));$("playlistDetailTitle").textContent=`${playlistIcon(p.name)} ${p.name}`;$("playlistDetailInfo").textContent=`${list.length} ${list.length===1?"canción":"canciones"}`;await renderSongs(list,"",$("playlistDetailSongs"));$("playlistDetailSongs").querySelectorAll(".song").forEach((row,i)=>{const sid=list[i]?.id;if(!sid)return;const actions=row.querySelector(".song-actions");const b=document.createElement("button");b.textContent="➖";b.title="Quitar de playlist";b.onclick=()=>removeSongFromPlaylist(id,sid);actions?.appendChild(b)})}
window.openPlaylistDetail=openPlaylistDetail;
async function removeSongFromPlaylist(pid,sid){const r=await supabaseClient.from("playlist_songs").delete().eq("playlist_id",pid).eq("song_id",sid);if(r.error){status("No se pudo quitar: "+r.error.message,true);return}openPlaylistDetail(pid,false)}window.removeSongFromPlaylist=removeSongFromPlaylist;
async function playPlaylist(){if(!playlistDetailId)return;const p=playlists.find(x=>x.id===playlistDetailId);const r=await supabaseClient.from("playlist_songs").select("song_id").eq("playlist_id",playlistDetailId);if(r.error)return;queue=(r.data||[]).map(x=>songs.find(s=>s.id===x.song_id)).filter(Boolean);if(!queue.length){status("La playlist está vacía.",true);return}queuePos=0;await playSongById(queue[0].id)}
async function addSongToPlaylist(songId){if(!playlists.length){alert("Primero crea una playlist.");return}const options=playlists.map((p,i)=>`${i+1}. ${p.name}`).join("\n");const n=Number(prompt("Elige una playlist:\n\n"+options));if(!Number.isInteger(n)||n<1||n>playlists.length)return;const r=await supabaseClient.from("playlist_songs").insert({playlist_id:playlists[n-1].id,song_id:songId});if(r.error&&!String(r.error.message).toLowerCase().includes("duplicate")){status("No se pudo agregar: "+r.error.message,true);return}status("Canción agregada a la playlist.")}window.addSongToPlaylist=addSongToPlaylist;
async function editSong(id){const s=songs.find(x=>x.id===id);if(!s)return;const title=prompt("Título:",s.title);if(title===null)return;const artist=prompt("Artista:",s.artist||"Mi biblioteca");if(artist===null)return;const r=await supabaseClient.from("songs").update({title:title.trim()||s.title,artist:artist.trim()||"Mi biblioteca"}).eq("id",id);if(r.error){status("No se pudo editar: "+r.error.message,true);return}await loadSongs()}window.editSong=editSong;
async function deleteSong(id){const s=songs.find(x=>x.id===id);if(!s)return;if(!confirm(`¿Eliminar "${s.title}"?\n\nSe quitará de tu biblioteca y del dispositivo.`))return;await removeOfflineAudio(id);let r=await supabaseClient.storage.from(BUCKET).remove([s.storage_path,...(s.cover_path?[s.cover_path]:[])]);if(r.error){status("No se pudo eliminar el archivo: "+r.error.message,true);return}r=await supabaseClient.from("songs").delete().eq("id",id);if(r.error){status("No se pudo eliminar: "+r.error.message,true);return}if(index>=0&&songs[index]?.id===id){audio.pause();audio.removeAttribute("src");audio.load();index=-1;localStorage.removeItem(CURRENT_KEY);nowTitle.textContent="Nada reproduciéndose";nowArtist.textContent="Mi biblioteca";nowCover.innerHTML="🎵";play.textContent="▶"}await loadSongs();status("🗑️ Canción eliminada.")}window.deleteSong=deleteSong;
function updateProfile(){session().then(s=>{if(s){$("profileEmail").textContent=s.user.email||"Usuario";$("profileStats").textContent=`${songs.length} ${songs.length===1?"canción":"canciones"} en tu biblioteca.`;$("accountBtn").textContent="Cerrar sesión"}else{$("profileEmail").textContent="Invitado";$("profileStats").textContent="Inicia sesión para usar tu biblioteca.";$("accountBtn").textContent="Iniciar sesión"}})}
function showAppView(view,hash=true){const valid=["home","search","favorites","playlists","playlistDetail","profile"];if(!valid.includes(view))view="home";currentView=view;["home","search","favorites","playlists","playlistDetail","profile"].forEach(v=>$(v+"View")?.classList.toggle("hidden",v!==view));document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.view===view));if(hash)history.replaceState(null,"",view==="home"?location.pathname:"#"+view);if(view==="home")renderSongs(songs,"Biblioteca");if(view==="search")renderSongs(filterSongs(search?.value),"Resultados de búsqueda",$("searchLibrary"));if(view==="favorites")renderFavorites();if(view==="playlists")renderPlaylists();if(view==="profile")updateProfile()}
window.showAppView=showAppView;
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showAppView(b.dataset.view));
if(search)search.oninput=()=>{if(currentView!=="search")showAppView("search");renderSongs(filterSongs(search.value),"Resultados de búsqueda",$("searchLibrary"))};
$("sortSelect")?.addEventListener("change",()=>renderSongs(songs,"Biblioteca"));$("offlineFilter")?.addEventListener("change",()=>renderSongs(songs,"Biblioteca"));
$("newPlaylist")?.addEventListener("click",createPlaylist);$("savePlaylist")?.addEventListener("click",savePlaylist);$("closePlaylist")?.addEventListener("click",()=>$("playlistPanel").classList.add("hidden"));$("backPlaylists")?.addEventListener("click",()=>showAppView("playlists"));$("playPlaylist")?.addEventListener("click",playPlaylist);
play.onclick=async()=>{if(index<0&&songs.length){await playSongById(songs[0].id)}else if(audio.paused){try{await audio.play()}catch{}}else audio.pause()};$("prev").onclick=()=>playPrev();$("next").onclick=()=>playNext();$("shuffle").onclick=()=>{shuffleOn=!shuffleOn;localStorage.setItem("miMusicaShuffle",shuffleOn?"1":"0");updatePlayerButtons()};$("repeat").onclick=()=>{repeatOn=!repeatOn;localStorage.setItem("miMusicaRepeat",repeatOn?"1":"0");updatePlayerButtons()};
function updatePlayerButtons(){$("shuffle")?.classList.toggle("active",shuffleOn);$("repeat")?.classList.toggle("active",repeatOn)}
function playNext(){if(queue.length&&queuePos>=0){queuePos=(queuePos+1)%queue.length;playSongById(queue[queuePos].id);return}if(!songs.length)return;let n;if(shuffleOn){n=Math.floor(Math.random()*songs.length);if(songs.length>1&&n===index)n=(n+1)%songs.length}else n=(index+1)%songs.length;playSongById(songs[n].id)}
function playPrev(){if(!songs.length)return;playSongById(songs[(index-1+songs.length)%songs.length].id)}
audio.ontimeupdate=()=>{if(seek)seek.value=audio.duration?(audio.currentTime/audio.duration)*100:0;if(current)current.textContent=fmt(audio.currentTime);if(duration)duration.textContent=fmt(audio.duration)};audio.onplay=()=>{play.textContent="⏸";document.body.classList.add("audio-playing")};audio.onpause=()=>{play.textContent="▶";document.body.classList.remove("audio-playing")};audio.onended=()=>{if(repeatOn){audio.currentTime=0;audio.play();return}playNext()};seek.oninput=()=>{if(audio.duration)audio.currentTime=(seek.value/100)*audio.duration};
const accountBtn=$("accountBtn"),authPanel=$("authPanel"),authSubmit=$("authSubmit"),switchAuth=$("switchAuth"),closeAuth=$("closeAuth"),authTitle=$("authTitle"),authMessage=$("authMessage");let signUpMode=false;
accountBtn.onclick=async()=>{const s=await session();if(s){await supabaseClient.auth.signOut();songs=[];favorites.clear();playlists=[];updateProfile();showAppView("profile");renderSongs([])}else authPanel.classList.remove("hidden")};closeAuth.onclick=()=>authPanel.classList.add("hidden");switchAuth.onclick=()=>{signUpMode=!signUpMode;authTitle.textContent=signUpMode?"Crear cuenta":"Iniciar sesión";authSubmit.textContent=signUpMode?"Registrarme":"Iniciar sesión";switchAuth.textContent=signUpMode?"Ya tengo una cuenta":"Crear cuenta";authMessage.textContent=signUpMode?"Crea una cuenta para usar tu biblioteca.":"Accede a tu biblioteca de Mi Música."};authSubmit.onclick=async()=>{const email=$("email").value.trim(),password=$("password").value;if(!email||password.length<6){alert("Escribe un correo y una contraseña de al menos 6 caracteres.");return}const r=signUpMode?await supabaseClient.auth.signUp({email,password}):await supabaseClient.auth.signInWithPassword({email,password});if(r.error){alert(r.error.message);return}authPanel.classList.add("hidden");await loadSongs();updateProfile()};
supabaseClient.auth.onAuthStateChange(()=>{setTimeout(()=>{loadSongs();updateProfile()},0)});
updatePlayerButtons();(async()=>{const s=await session();if(s){const last=localStorage.getItem(CURRENT_KEY);await loadSongs();if(last&&songs.some(x=>x.id===last)){const sng=songs.find(x=>x.id===last);nowTitle.textContent=sng.title;nowArtist.textContent=sng.artist||"Mi biblioteca"}}else{uploadEnabled(false);updateProfile()}showAppView(location.hash.replace("#","")||"home",false)})();
